"""Shared timeout contracts that cross application and deployment boundaries."""

from typing import Final

SEED_ONBOARDING_WAIT_SECONDS: Final = 12 * 60
SEED_ONBOARDING_ROUTE_TIMEOUT_SECONDS: Final = 14 * 60
PUBLIC_PROXY_READ_TIMEOUT_SECONDS: Final = SEED_ONBOARDING_ROUTE_TIMEOUT_SECONDS + 60
AI_STAGE_EXECUTION_TIMEOUT_SECONDS: Final = 4 * 60
ARQ_JOB_TIMEOUT_OVERHEAD_SECONDS: Final = 30
